# Generated by Django 4.2.4 on 2023-08-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='middleName',
            field=models.CharField(help_text='Введите свое отчество', max_length=150, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surname',
            field=models.CharField(help_text='Введите свою фамилию', max_length=150, verbose_name='Фамилия'),
        ),
    ]
