# Generated by Django 4.2 on 2023-09-09 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_typecard_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseamount',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountapp.сard', verbose_name='Карта клиента'),
        ),
    ]
