# Generated by Django 4.2 on 2023-09-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_purchaseamount_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сard',
            name='cardId',
            field=models.IntegerField(unique=True, verbose_name='Код карты'),
        ),
    ]
